### ISSUE TITLE
No data in /gps/imu topic

### ISSUE THREAD

**Issue by jayjayhee** [novatel/novatel_oem7_driver#10]
Hi,
I'm experiencing an issue when using usb operation method. There were 3 error messages reported as follows:

`[ERROR] [1598343835.180147191]: Attempt 0: timed out waiting for response.`
`[ERROR] [1598343835.196250946]: AACmd 'LOG INSCONFIGB ONTIME 300' : 'ERROR:Trigger ONTIME not valid for this log'`
`[ERROR] [1598343835.260403646]: AACmd 'LOG CORRIMUSB ONTIME 0.01' : 'ERROR:Invalid Message. Field = 2'`

The complete command window is shown below:
```
PARAMETERS
 * /novatel/oem7/oem7_msgs/BDSEPHEMERIS: 1696
 * /novatel/oem7/oem7_msgs/BESTPOS: 42
 * /novatel/oem7/oem7_msgs/BESTUTM: 726
 * /novatel/oem7/oem7_msgs/BESTVEL: 99
 * /novatel/oem7/oem7_msgs/CORRIMUS: 2264
 * /novatel/oem7/oem7_msgs/GALFNAVEPHEMERIS: 1310
 * /novatel/oem7/oem7_msgs/GALINAVEPHEMERIS: 1309
 * /novatel/oem7/oem7_msgs/GLOEPHEMERIS: 723
 * /novatel/oem7/oem7_msgs/HEADING2: 1335
 * /novatel/oem7/oem7_msgs/IMURATECORRIMUS: 1362
 * /novatel/oem7/oem7_msgs/INSCONFIG: 1945
 * /novatel/oem7/oem7_msgs/INSPVAS: 508
 * /novatel/oem7/oem7_msgs/INSPVAX: 1465
 * /novatel/oem7/oem7_msgs/INSSTDEV: 2051
 * /novatel/oem7/oem7_msgs/INSUPDATESTATUS: 1825
 * /novatel/oem7/oem7_msgs/PSRDOP2: 1163
 * /novatel/oem7/oem7_msgs/RANGE: 43
 * /novatel/oem7/oem7_msgs/RAWEPHEM: 41
 * /novatel/oem7/oem7_msgs/RAWIMUSX: 1462
 * /novatel/oem7/oem7_msgs/RXSTATUS: 93
 * /novatel/oem7/oem7_msgs/TIME: 101
 * /novatel/oem7/receivers/main/BESTPOS/frame_id: gps
 * /novatel/oem7/receivers/main/BESTPOS/topic: /novatel/oem7/bes...
 * /novatel/oem7/receivers/main/BESTUTM/frame_id: gps
 * /novatel/oem7/receivers/main/BESTUTM/topic: /novatel/oem7/bes...
 * /novatel/oem7/receivers/main/BESTVEL/frame_id: gps
 * /novatel/oem7/receivers/main/BESTVEL/topic: /novatel/oem7/bes...
 * /novatel/oem7/receivers/main/CORRIMU/frame_id: gps
 * /novatel/oem7/receivers/main/CORRIMU/topic: /novatel/oem7/cor...
 * /novatel/oem7/receivers/main/GPSFix/frame_id: gps
 * /novatel/oem7/receivers/main/GPSFix/topic: /gps/gps
 * /novatel/oem7/receivers/main/HEADING2/frame_id: gps
 * /novatel/oem7/receivers/main/HEADING2/topic: /novatel/oem7/hea...
 * /novatel/oem7/receivers/main/IMU/frame_id: gps
 * /novatel/oem7/receivers/main/IMU/topic: /gps/imu
 * /novatel/oem7/receivers/main/INSCONFIG/frame_id: gps
 * /novatel/oem7/receivers/main/INSCONFIG/queue_size: 10
 * /novatel/oem7/receivers/main/INSCONFIG/topic: /novatel/oem7/ins...
 * /novatel/oem7/receivers/main/INSPVA/frame_id: gps
 * /novatel/oem7/receivers/main/INSPVA/topic: /novatel/oem7/inspva
 * /novatel/oem7/receivers/main/INSPVAX/frame_id: gps
 * /novatel/oem7/receivers/main/INSPVAX/queue_size: 10
 * /novatel/oem7/receivers/main/INSPVAX/topic: /novatel/oem7/ins...
 * /novatel/oem7/receivers/main/INSSTDEV/frame_id: gps
 * /novatel/oem7/receivers/main/INSSTDEV/queue_size: 10
 * /novatel/oem7/receivers/main/INSSTDEV/topic: /novatel/oem7/ins...
 * /novatel/oem7/receivers/main/NavSatFix/frame_id: gps
 * /novatel/oem7/receivers/main/NavSatFix/topic: /gps/fix
 * /novatel/oem7/receivers/main/Oem7RawMsg/frame_id: gps
 * /novatel/oem7/receivers/main/Oem7RawMsg/queue_size: 200
 * /novatel/oem7/receivers/main/Oem7RawMsg/topic: /novatel/oem7/oem...
 * /novatel/oem7/receivers/main/RXSTATUS/frame_id: gps
 * /novatel/oem7/receivers/main/RXSTATUS/queue_size: 10
 * /novatel/oem7/receivers/main/RXSTATUS/topic: /novatel/oem7/rxs...
 * /novatel/oem7/receivers/main/TIME/frame_id: gps
 * /novatel/oem7/receivers/main/TIME/topic: /novatel/oem7/time
 * /novatel/oem7/receivers/main/oem7_if: Oem7ReceiverPort
 * /novatel/oem7/receivers/main/oem7_msg_decoder: Oem7MessageDecoder
 * /novatel/oem7/receivers/main/oem7_msg_handlers: ['BESTPOSHandler'...
 * /novatel/oem7/receivers/main/oem7_publish_unknown_oem7raw: True
 * /novatel/oem7/receivers/main/oem7_raw_msgs: ['BESTPOS', 'BEST...
 * /novatel/oem7/receivers/main/oem7_tty_baud: 9600
 * /novatel/oem7/receivers/main/oem7_tty_name: /dev/ttyUSB0
 * /novatel/oem7/receivers/main/receiver_init_commands: ['UNLOGALL THISPO...
 * /novatel/oem7/supported_imus/0/name: Unknown
 * /novatel/oem7/supported_imus/0/rate: 0
 * /novatel/oem7/supported_imus/1/name: Honeywell HG1700 AG1
 * /novatel/oem7/supported_imus/1/rate: 100
 * /novatel/oem7/supported_imus/11/name: Honeywell HG1700 ...
 * /novatel/oem7/supported_imus/11/rate: 100
 * /novatel/oem7/supported_imus/12/name: Honeywell HG1700 ...
 * /novatel/oem7/supported_imus/12/rate: 100
 * /novatel/oem7/supported_imus/13/name: iMAR ilMU-FSAS
 * /novatel/oem7/supported_imus/13/rate: 200
 * /novatel/oem7/supported_imus/16/name: KVH CPT IMU
 * /novatel/oem7/supported_imus/16/rate: 200
 * /novatel/oem7/supported_imus/19/name: Northrop Grumman ...
 * /novatel/oem7/supported_imus/19/rate: 200
 * /novatel/oem7/supported_imus/20/name: Honeywell HG1930 ...
 * /novatel/oem7/supported_imus/20/rate: 100
 * /novatel/oem7/supported_imus/26/name: Northrop Grumman ...
 * /novatel/oem7/supported_imus/26/rate: 100
 * /novatel/oem7/supported_imus/27/name: Honeywell HG1900 ...
 * /novatel/oem7/supported_imus/27/rate: 100
 * /novatel/oem7/supported_imus/28/name: Honeywell HG1930 ...
 * /novatel/oem7/supported_imus/28/rate: 100
 * /novatel/oem7/supported_imus/31/name: Analog Devices AD...
 * /novatel/oem7/supported_imus/31/rate: 200
 * /novatel/oem7/supported_imus/32/name: Sensonor STIM300
 * /novatel/oem7/supported_imus/32/rate: 125
 * /novatel/oem7/supported_imus/33/name: KVH1750 IMU
 * /novatel/oem7/supported_imus/33/rate: 200
 * /novatel/oem7/supported_imus/4/name: Honeywell HG1700 ...
 * /novatel/oem7/supported_imus/4/rate: 100
 * /novatel/oem7/supported_imus/41/name: Epson G320N
 * /novatel/oem7/supported_imus/41/rate: 125
 * /novatel/oem7/supported_imus/45/name: KVH 1725 IMU?
 * /novatel/oem7/supported_imus/45/rate: 200
 * /novatel/oem7/supported_imus/5/name: Honeywell HG1700 ...
 * /novatel/oem7/supported_imus/5/rate: 100
 * /novatel/oem7/supported_imus/52/name: Litef microIMU
 * /novatel/oem7/supported_imus/52/rate: 200
 * /novatel/oem7/supported_imus/56/name: Sensonor STIM300,...
 * /novatel/oem7/supported_imus/56/rate: 125
 * /novatel/oem7/supported_imus/58/name: Honeywell HG4930 ...
 * /novatel/oem7/supported_imus/58/rate: 200
 * /novatel/oem7/supported_imus/61/name: Epson G370N
 * /novatel/oem7/supported_imus/61/rate: 200
 * /novatel/oem7/supported_imus/62/name: Epson G320N - 200Hz
 * /novatel/oem7/supported_imus/62/rate: 200
 * /novatel/oem7/supported_imus/8/name: Northrop Grumman ...
 * /novatel/oem7/supported_imus/8/rate: 200
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /novatel/oem7/
    driver (nodelet/nodelet)
  /novatel/oem7/receivers/
    main (nodelet/nodelet)
  /novatel/oem7/receivers/main/
    config (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [29472]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 6e23324e-e6b6-11ea-91c3-04d4c4070b48
process[rosout-1]: started with pid [29483]
started core service [/rosout]
process[novatel/oem7/driver-2]: started with pid [29490]
process[novatel/oem7/receivers/main-3]: started with pid [29491]
process[novatel/oem7/receivers/main/config-4]: started with pid [29492]
[ INFO] [1598348180.202546983]: Loading nodelet /novatel/oem7/receivers/main of type novatel_oem7_driver/Oem7MessageNodelet to manager /novatel/oem7/driver with the following remappings:
[ INFO] [1598348180.205429035]: waitForService: Service [/novatel/oem7/driver/load_nodelet] has not been advertised, waiting...
[ INFO] [1598348180.210293471]: Loading nodelet /novatel/oem7/receivers/main/config of type novatel_oem7_driver/Oem7ConfigNodelet to manager /novatel/oem7/driver with the following remappings:
[ INFO] [1598348180.211004232]: Initializing nodelet with 4 worker threads.
[ INFO] [1598348180.212195143]: waitForService: Service [/novatel/oem7/driver/load_nodelet] has not been advertised, waiting...
[ INFO] [1598348180.227829993]: waitForService: Service [/novatel/oem7/driver/load_nodelet] is now available.
[ INFO] [1598348180.234195176]: waitForService: Service [/novatel/oem7/driver/load_nodelet] is now available.
[ INFO] [1598348180.243496798]: /novatel/oem7/receivers/main: Oem7MessageNodelet v.1.1.0; May 30 2020 10:12:47
[ INFO] [1598348180.252521386]: Oem7MessageDecoderLib version: 0.1.11
[ INFO] [1598348180.254761878]: topic [/novatel/oem7/bestpos]: frame_id: 'gps'; q size: 100
[ INFO] [1598348180.256191702]: topic [/novatel/oem7/bestvel]: frame_id: 'gps'; q size: 100
[ INFO] [1598348180.257473625]: topic [/novatel/oem7/bestutm]: frame_id: 'gps'; q size: 100
[ INFO] [1598348180.258732296]: topic [/novatel/oem7/inspva]: frame_id: 'gps'; q size: 100
[ INFO] [1598348180.260245293]: topic [/gps/gps]: frame_id: 'gps'; q size: 100
[ INFO] [1598348180.261554933]: topic [/gps/fix]: frame_id: 'gps'; q size: 100
[ INFO] [1598348180.262936746]: topic [/gps/imu]: frame_id: 'gps'; q size: 100
[ INFO] [1598348180.264317317]: topic [/novatel/oem7/corrimu]: frame_id: 'gps'; q size: 100
[ INFO] [1598348180.265674452]: topic [/novatel/oem7/insstdev]: frame_id: 'gps'; q size: 10
[ INFO] [1598348180.267003056]: topic [/novatel/oem7/inspvax]: frame_id: 'gps'; q size: 10
[ INFO] [1598348180.268502190]: topic [/novatel/oem7/insconfig]: frame_id: 'gps'; q size: 10
[ INFO] [1598348180.270385174]: topic [/novatel/oem7/heading2]: frame_id: 'gps'; q size: 100
[ INFO] [1598348180.271864116]: topic [/novatel/oem7/rxstatus]: frame_id: 'gps'; q size: 10
[ INFO] [1598348180.273314737]: topic [/novatel/oem7/time]: frame_id: 'gps'; q size: 100
[ INFO] [1598348180.274743779]: Oem7 Raw message 'BESTPOS' will be published.
[ INFO] [1598348180.274809257]: Oem7 Raw message 'BESTVEL' will be published.
[ INFO] [1598348180.274868376]: Oem7 Raw message 'INSPVAX' will be published.
[ INFO] [1598348180.274892170]: Oem7 Raw message 'INSUPDATESTATUS' will be published.
[ INFO] [1598348180.274911023]: Oem7 Raw message 'RAWIMUSX' will be published.
[ INFO] [1598348180.274940432]: Oem7 Raw message 'RAWEPHEM' will be published.
[ INFO] [1598348180.274957220]: Oem7 Raw message 'GLOEPHEMERIS' will be published.
[ INFO] [1598348180.274977744]: Oem7 Raw message 'BDSEPHEMERIS' will be published.
[ INFO] [1598348180.274995641]: Oem7 Raw message 'GALFNAVEPHEMERIS' will be published.
[ INFO] [1598348180.275015994]: Oem7 Raw message 'GALINAVEPHEMERIS' will be published.
[ INFO] [1598348180.275037736]: Oem7 Raw message 'RANGE' will be published.
[ INFO] [1598348180.275053870]: Oem7 Raw message 'HEADING2' will be published.
[ INFO] [1598348180.275076510]: Oem7 Raw message 'TIME' will be published.
[ INFO] [1598348180.275100243]: Oem7 Raw message 'RXSTATUS' will be published.
[ INFO] [1598348180.275127978]: Oem7 Raw message 'INSCONFIG' will be published.
[ INFO] [1598348180.275803989]: topic [/novatel/oem7/oem7raw]: frame_id: 'gps'; q size: 200
[ INFO] [1598348180.280279513]: Oem7SerialPort['/dev/ttyUSB0' : 9600]
[ INFO] [1598348180.280453641]: Oem7SerialPort open: '1; err: system:0
[ INFO] [1598348180.280502166]: Oem7SerialPort set_option baud_rate: '9600 : system:0
[ INFO] [1598348180.282714414]: /novatel/oem7/receivers/main/config: Oem7ConfigNodelet v.1.1.0; May 30 2020 10:12:47
[ERROR] [1598348183.286857710]: Attempt 0: timed out waiting for response.
[ INFO] [1598348183.289295001]: AACmd 'UNLOGALL THISPORT' : 'OK'
[ INFO] [1598348183.296117783]: AACmd 'LOG INSCONFIGB ONCE' : 'OK'
[ INFO] [1598348183.300674495]: IMU: 'Epson G320N', rate= 125
[ERROR] [1598348183.302643357]: AACmd 'LOG INSCONFIGB ONTIME 300' : 'ERROR:Trigger ONTIME not valid for this log'
[ INFO] [1598348183.309520697]: AACmd 'LOG RXSTATUSB ONCHANGED' : 'OK'
[ INFO] [1598348183.315281163]: AACmd 'LOG BESTPOSB ONTIME 0.1' : 'OK'
[ INFO] [1598348183.323326704]: AACmd 'LOG BESTVELB ONTIME 0.1' : 'OK'
[ INFO] [1598348183.331940016]: AACmd 'LOG BESTUTMB ONTIME 1' : 'OK'
[ INFO] [1598348183.338498924]: AACmd 'LOG HEADING2B ONNEW' : 'OK'
[ INFO] [1598348183.345930291]: AACmd 'LOG PSRDOP2B ONCHANGED' : 'OK'
[ INFO] [1598348183.352300335]: AACmd 'LOG INSPVASB ONTIME 0.02' : 'OK'
[ INFO] [1598348183.358375687]: AACmd 'LOG INSPVAXB ONTIME 1' : 'OK'
[ERROR] [1598348183.365567507]: AACmd 'LOG CORRIMUSB ONTIME 0.01' : 'ERROR:Invalid Message. Field = 2'
[ INFO] [1598348183.371581626]: AACmd 'LOG INSSTDEVB ONTIME 1' : 'OK'
[ INFO] [1598348183.378204374]: AACmd 'LOG TIMEB ONTIME 1' : 'OK'
[ INFO] [1598348183.387402979]: AACmd 'LOG RAWIMUSXB ONNEW' : 'OK'
[ INFO] [1598348183.395132850]: AACmd 'LOG INSUPDATESTATUSB ONNEW' : 'OK'
[ INFO] [1598348183.402163923]: AACmd 'LOG RAWEPHEMB ONNEW' : 'OK'
[ INFO] [1598348183.410159415]: AACmd 'LOG GLOEPHEMERISB ONNEW' : 'OK'
[ INFO] [1598348183.417501333]: AACmd 'LOG BDSEPHEMERISB ONNEW' : 'OK'
[ INFO] [1598348183.441648973]: AACmd 'LOG GALFNAVEPHEMERISB ONNEW' : 'OK'
[ INFO] [1598348183.450066874]: AACmd 'LOG GALINAVEPHEMERISB ONNEW' : 'OK'
[ INFO] [1598348183.460385374]: AACmd 'LOG RANGEB ONTIME 1' : 'OK'
[ INFO] [1598348183.460781212]: Oem7 configuration completed.
```

Additionally, although configuration is completed despite errors and the `/gps/imu` and `/corrimu/` topics are published, there isn't any imu data under these topics.

**Comment by jayjayhee** [comment]
I actually don't consider this as a bug but somehow it shows a label of bug. I guess I misclicked something...

**Comment by novatel-applications-engineering** [comment]
Hi @jayjayhee,
The settings of novatel_oem7_driver must match the abilities of the receiver being used with the driver. I suspect that your current novatel_oem7_driver settings are not compatible with your receiver.

This should be handled as a support case with NovAtel Customer Support. You may start a case by reaching out to us at support.novatel@hexagon.com. I'll watch for the case and take it when it comes in. Please include any customized .yaml files. Once the support case is open I'll send you a link to a location where you can also upload sample data such as bag files.

Thank you, talk to you soon,
NovAtel Customer Support

**Comment by jayjayhee** [comment]
Thanks for your response. I really appreciate it.

**Comment by Daniel-git-Hub-2021** [comment]
Hy @jayjayhee, 

I am having the same problem as you, would it be possible to say what you did to get around this situation? 

I’m stuck with a few days to solve this, since the data published in gps / imu or novatel / oem7 / corrimu are zeroed.

Tank You!

**Comment by juhe9842** [comment]
Hi @Daniel-git-Hub-2021 

It's been quite a while since the time I solved this problem so I can barely remember the details I've been through. But I will try to make it clear to you. Those errors are mainly because the firmware of the imu doesn't match this driver. This driver has been updated for the new firmware and I was usin the old one. The best solution I would suggest is to update the firmware of the imu. If it's not available, you can also modify this driver based on the user manual to get the data you want. According to my memory, the topic "CORRIMUDATA" has been modified so you need to change it back to the old version (Compare the two versions of manual to see what has been changed).

**Comment by Daniel-git-Hub-2021** [comment]
@juhe9842 

Thank you for the information! I will calmly analyze the imu driver that is currently active! Your response was of great help. 

have a good week.

**Comment by novatel-applications-engineering** [comment]
Hi @Daniel-git-Hub-2021,

As mentioned in the response above, the settings of novatel_oem7_driver must match the OEM7 receiver and IMU (or combined OEM7 receiver + IMU enclosure product) being used with the driver. I suspect that your current novatel_oem7_driver settings are not compatible with your receiver. For example, you are using an OEM6 generation product or a product with an unsupported IMU. 

If you are unable to resolve the issue on your own, we'd be happy to assist through a support case with NovAtel Customer Support. You may start a case by reaching out to us at support.novatel@hexagon.com. We'll watch for the case and take it when it comes in. Please include any customized .yaml files. 

Thank you,
NovAtel Customer Support

**Comment by Daniel-git-Hub-2021** [comment]
Hi, @novatel-applications-engineering,

My Novatel receiver is an OEM7 (PwrPak7D-E1) with integrated IMON EPSON G320N. I believe it is something related to SPAN initialization. Every time I turn the receiver off, it stays OFF. 

In addition, the INS light is only flashing yellow, it does not stabilize for anything. Would you have any tips on how I can proceed?

Grateful for your help.

**Comment by Daniel-git-Hub-2021** [comment]
Hi, @novatel-applications-engineering,

My Novatel receiver is an OEM7 (PwrPak7D-E1) with integrated IMU EPSON G320N. I believe it is something related to SPAN initialization. Every time I turn the receiver off, it stays OFF.

In addition, the INS light is only flashing yellow, it does not stabilize for anything. Would you have any tips on how I can proceed?

Grateful for your help.

**Comment by Daniel-git-Hub-2021** [comment]
@novatel-applications-engineering, 

I believe I found out where the problem is.

I need to modify the sdt_init_commands.yaml file where I will inform the imu data correctly as: 

"CONNECTIMU SPI EPSON_G320"

"SETINSTRANSLATION ANT1"

"SETINSTRANSLATION ANT2"

In addition to the rotations.

However, I don't know exactly how to make these changes to this file.

When I did this for "NovAtelApplicationSuite" it worked and the INS light stabilized in green and I got information from the IMU.

However, when I turn off the Receiver these settings are cleared and then I would have to enter NovAtelApplicationSuite again and set everything up again.

I believe that if configured correctly, when I initialize the file through ROS this initialization / configuration will occur correctly.

Could you help me edit this file?

Grateful for the attention, and I look forward to your return.

**Comment by novatel-applications-engineering** [comment]
Hi @Daniel-git-Hub-2021,
We have responded to you through the NovAtel support queue. Full details and examples of modifying the receiver configuration via the std_init_commands.yaml file can be found here: [http://wiki.ros.org/novatel_oem7_driver/configuration](http://wiki.ros.org/novatel_oem7_driver/configuration)

**Comment by MCFurry** [comment]
Just for reference to anyone who is reading this topic.

I recently connected a SMART7-S receiver to this driver and also did not have any `/gps/imu` messages published.

I tried manually executing the `LOG CORRIMUSB ONTIME 0.01` command which resulted in an error message. 
Then I found:
![image](https://user-images.githubusercontent.com/16306445/115237472-e484d980-a11c-11eb-8b30-09d005ce66f8.png)
ref: https://docs.novatel.com/OEM7/Content/SPAN_Logs/CORRIMUDATA.htm
And enabling CORRIMUDATA log did work!

Hence I concluded that the firmware on my receiver was too old to contain the CORRIMUS log that this ROS driver is requesting by default. Upgrading the receiver firmware indeed fixed that!

**Comment by ajay1606** [comment]
@novatel-applications-engineering , 
Hello, thanks for sharing information here, Indeed i was also stuck with same issue. After going through all your comments i realized root cause of issue. It was very much helpful in understanding actual cause.

But unfortunately, i couldn't able to fix the issue. We have two units of PwrPak7D-E1 receivers.  

**Receiver 1:** 
![image](https://user-images.githubusercontent.com/29722843/133712735-c3dbb557-95a5-45f6-8c65-df31530bb9e7.png)
Using Receiver 1: am able to run novatel_oem7_driver without any issues.

**Receiver 2:**
![image](https://user-images.githubusercontent.com/29722843/133712783-cc4c1a61-bd3d-4e8f-aa44-aeb13c5f2c5a.png)
With receiver 2 am getting following error message continously.

**Error Message:** 
![error](https://user-images.githubusercontent.com/29722843/133713003-47fa083d-021a-4f5c-aefc-5ef27f253109.png)

We greatly appreciate if you could mention specific setting that needs to configure. 

Regards,
Ajay

**Comment by novatel-applications-engineering** [comment]
Thank you for reaching out @ajay1606! It looks like a case was opened up in the NovAtel support queue on your issue and our team will help you out there.

**Comment by programath** [comment]
> @novatel-applications-engineering , Hello, thanks for sharing information here, Indeed i was also stuck with same issue. After going through all your comments i realized root cause of issue. It was very much helpful in understanding actual cause.
> 
> But unfortunately, i couldn't able to fix the issue. We have two units of PwrPak7D-E1 receivers.
> 
> **Receiver 1:** ![image](https://user-images.githubusercontent.com/29722843/133712735-c3dbb557-95a5-45f6-8c65-df31530bb9e7.png) Using Receiver 1: am able to run novatel_oem7_driver without any issues.
> 
> **Receiver 2:** ![image](https://user-images.githubusercontent.com/29722843/133712783-cc4c1a61-bd3d-4e8f-aa44-aeb13c5f2c5a.png) With receiver 2 am getting following error message continously.
> 
> **Error Message:** ![error](https://user-images.githubusercontent.com/29722843/133713003-47fa083d-021a-4f5c-aefc-5ef27f253109.png)
> 
> We greatly appreciate if you could mention specific setting that needs to configure to fix the this error message.
> 
> Regards, Ajay

Hi Ajay,

Seems I encountered the same issue with yours.  Have you resolved it?
