### ISSUE TITLE
Noetic (Ubuntu 20.04) support

### ISSUE THREAD

**Issue by novatel-applications-engineering** [novatel/novatel_oem7_driver#11]
This driver does not currently support ROS Noetic. If you want this, please thumbs-up this issue to help us weigh the level of interest in implementing this support.

**Comment by uchaudh** [comment]
We could really use the noetic driver.

**Comment by novatel-applications-engineering** [comment]
> We could really use the noetic driver.

Hi @uchaudh, the official release for Noetic is now available in the ROS distribution. It can be installed via `apt-get install ros-noetic-novatel-oem7-driver`.
