### ISSUE TITLE
Getting accuracy information from ROS node

### ISSUE THREAD

**Issue by yucedagonurcan** [novatel/novatel_oem7_driver#12]
Hello,

How can I get the current accuracy information from gnss?

I am able to get BESTPOS sentence but it contadan lat and long deviation separately. I want to get accuracy field in the web ui specifically. What do I need to compute to get that?

Have a great day.

**Comment by novatel-applications-engineering** [comment]
@yucedagonurcan please open a support case with us by emailing support.novatel@hexagon.com.

Thank you and have an excellent day.
