### ISSUE TITLE
Conflicting corrimu log

### ISSUE THREAD

**Issue by ozzdemir** [novatel/novatel_oem7_driver#14]
**Describe the bug**
When we are using novatel_oem7_driver, we observed that corrimu log is continuously conflicting. It can be seen in the two figures below. First one is timeseries plot of it and second one is the datapoint only version of it.

**Expected behavior**
IMU should report correct acceleration and rotational velocities.

**Screenshots**
![novatel_corrimu_conflict](https://user-images.githubusercontent.com/30624975/106242768-4407d300-6219-11eb-97e5-0663151ad5a5.png)
![novatel_corrimu_conflict_dotsonly](https://user-images.githubusercontent.com/30624975/106242767-42d6a600-6219-11eb-9354-9dcf5c301228.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu]
 - Version [18.04]

**Additional context**
Following init command is used to initialize the driver using both from eth, and serial; no change.
[std_init_commands.zip](https://github.com/novatel/novatel_oem7_driver/files/5892171/std_init_commands.zip)

**Comment by novatel-applications-engineering** [comment]
@ozzdemir this should be handled as a support case with NovAtel Customer Support. You may start a case by reaching out to us at support.novatel@hexagon.com. Please reference this issue (https://github.com/novatel/novatel_oem7_driver/issues/14), so we can refer to the original information you provided in GitHub. Once the support case is open I'll send you a link to a location where you can also upload sample data such as bag files.

Thank you, talk to you soon,
NovAtel Customer Support
