### ISSUE TITLE
Are there any plans for releasing this in ROS2?

### ISSUE THREAD

**Issue by msmcconnell** [novatel/novatel_oem7_driver#2]
Are there any plans for releasing this driver in ROS2 and if so could you provide an approximate timeline or is external contribution necessary?

**Comment by novatel-applications-engineering** [comment]
@msmcconnell Great question, thank you for raising it. 

The ROS2 implementation is currently under consideration but no specific timeline is available. 

Anyone who is also interested in this is invited to up-vote the original question above.

**Comment by novatel-applications-engineering** [comment]
Update: a project to create the ROS2 implementation of novatel_oem7_driver is now underway. We a targeting a Q3 2021 release.

**Comment by tgbosch** [comment]
Are there any news if you will be able to meet the Q3 2021 target?
Would also be interesting to know, if you will support a Windows-native ROS2 environment?

**Comment by novatel-applications-engineering** [comment]
@tgbosch Yes, We are still on target for Q3 2021 release. 

A Windows-native ROS2 environment is on our radar, but there is no planned date for release.

**Comment by Timple** [comment]
ROS2 support doesn't seem added yet, why was this closed?

**Comment by novatel-applications-engineering** [comment]
@Timple Apologies! ROS2 is still on track for release. We will leave this open until the feature has been officially released.

**Comment by novatel-applications-engineering** [comment]
[FYI we have officially released ROS2 support as of December 8, 2021](https://novatel.com/about-us/news-releases/hexagon-novatel-delivers-ros-2-compatible-drivers-to-the-oem7-receiver)

All necessary files are available here on Github.
