### ISSUE TITLE
Novatel_OEM7_Driver on ROS Kinetic

### ISSUE THREAD

**Issue by jptalledo10** [novatel/novatel_oem7_driver#21]
I have an x86 Ubuntu platform running ROS Kinetic (I know it is old) and the Novatel OEM7 driver launches just fine but I don't see it publishes any data.

I tried the novatel_gps_driver and works fine. Just wondering what could be happening or if somebody is aware of incompatibilities with ROS Kinetic

**Comment by novatel-applications-engineering** [comment]
Hi @jptalledo10 thank you for your question! While ROS Kinetic is an older release, our novatel_oem7_driver supports three releases: noetic, melodic and kinetic. Please see the ROS driver wiki link [here](http://wiki.ros.org/action/edit/novatel_oem7_driver/). 

novatel_gps_driver is not a driver released by NovAtel and is not officially supported. 

If you are still having issues with the novatel_oem7_driver, please submit a support ticket to support.novatel@hexagon.com. The support portal will put you in touch with an Application Engineer at NovAtel that can help with any outstanding issues.
