### ISSUE TITLE
IMU covariance reporting incorrectly on 2.3.x

### ISSUE THREAD

**Issue by garyedwards** [novatel/novatel_oem7_driver#23]
**Describe the bug**
Using the latest `2.3.x` branch `linear_acceleration_covariance[0]` and `angular_velocity_covariance[0]` report `-1.0` which indicates no estimate for `linear_acceleration` and `angular_velocity` elements.

However the driver does publish data for these elements and I believe the driver should publish a covariance matrix of all zeros instead which will be interpreted as "covariance unknown".

See the [official api docs](http://docs.ros.org/en/api/sensor_msgs/html/msg/Imu.html)

**To Reproduce**
1. Checkout the 2.3.x branch
2. Run the driver
3. `rostopic echo /gps/imu`

**Expected behavior**
If the covariance is unknown a covariance matrix of all zeros should be published.

**Environment (please complete the following information):**
 - OS: ROS Melodic on Ubuntu Bionic
 - 2.3.x

**Comment by novatel-applications-engineering** [comment]
Hi @garyedwards, thank you for reporting this. We have added it to our queue of issues to fix and will provide the fix in a future release.
