### ISSUE TITLE
Feature request: ROS2 support

### ISSUE THREAD

**Issue by Timple** [novatel/novatel_oem7_driver#25]
**Is your feature request related to a problem? Please describe.**
ROS1 support ends in May 2025. So for us it's time to migrate to ROS2.

**Describe the solution you'd like**
A ROS2 driver for the Novatel gps systems.

**Describe alternatives you've considered**

**Additional context**
All our new robots will be developed ROS2 only. So if one would require GPS, this would be a blocking issue.

**Comment by novatel-applications-engineering** [comment]
Hi @Timple we are currently developing ROS2 support, expected Q3 2021 release.

**Comment by Timple** [comment]
Even though I commented in the other issue I did not realize it was the same repository. Apologies for the duplicate, tracking in #2

**Comment by novatel-applications-engineering** [comment]
ROS2 Alpha is available in the ros2-dev branch now.
