### ISSUE TITLE
Output orientation is not in the correct frame when using SETINSROTATION RBV

### ISSUE THREAD

**Issue by JTomasi** [novatel/novatel_oem7_driver#28]
Hello,

I am experiencing an issue with CPT7 and associated ROS driver. I am trying to setup the device so that the values obtained by the device are expressed in the Novatel defined vehicle frame. For example, if the vehicle was facing in the north direction on smooth, level ground, the orientation reported by the ROS driver would be identity q(0,0,0,1).
The device is currently mounted with the axes of the enclosure pointing in the following directions:

- x = backward
- y = left
- z = down

Since the device is not mounted in the recommended configuration, I understand that I must enter the rotation from the IMU body frame to the vehicle frame (RBV) so that the measurements made in the IMU body frame are expressed in the right, forward, up vehicle frame. To do this, I have done the following:

- SETINSROTATION RBV 180 0 -90
- SETINSROTATION USER 0 0 0

This performs a rotation in the ZXY order which should rotate the IMU body frame to be aligned with the Novatel defined user frame. For some reason, the orientation and IMU values output by the ROS driver are not in this frame. Instead, the orientation of the device indicates that the device is oriented in a left, forward, down convention instead. I have confirmed this by both analyzing the output orientation and output accelerations/velocities and have confirmed that the values are being reported in left, forward, down.

**An example**:
My vehicle is positioned on flat, level ground with a true heading of 228 degrees (pointing south-west). The output orientation reported in the /novatel/oem7/odom topic is:

- q.w = 0.0515
- q.x = 0.90287
- q.y = -0.4258
- q.z = -0.02967

Converting this to an euler angles in an XYZ convention gives:

- x: 176.097916
- y: -5.5913411
- z: 50.3071829

If we express this orientation in the ENU frame, this results in a left, forward, down vehicle frame. This is not the vehicle frame that we are expecting based off of the SETINSROTATION documentation.

Can you please indicate if I am missing any steps, misunderstood something, or advise on other things that I can try to remedy this issue?

**Comment by novatel-applications-engineering** [comment]
Hi there,

The questions on reference frames are being handled through NovAtel's support portal. NovAtel support is available through the email support.novatel@hexagon.com and can help with any ROS related inquiries. 

Thank you for using NovAtel's ROS driver
