### ISSUE TITLE
"Rostopic echo /gps/imu and /novatel/oem7/corrimu" no data output

### ISSUE THREAD

**Issue by RuanJiaJun** [novatel/novatel_oem7_driver#38]
I installed the novatel oem7 driver according to the wiki tutorial and filled in the configuration file correctly, but no data was output after entering "rostopic echo /gps/imu and /novatel/oem7/corrimu" in the terminal. The following is a screenshot of my actual problem. I sincerely ask friends to help analyze the reasons and provide solutions, thank you very much!

        First is my configuration file (std_init_commands.yaml):
![image](https://user-images.githubusercontent.com/73341802/141668667-54ee70ba-d343-48af-9f47-0247a6ea238f.png)
![image](https://user-images.githubusercontent.com/73341802/141668682-ae1b345d-5a9f-4ec8-9f97-761e8925d20e.png)
![image](https://user-images.githubusercontent.com/73341802/141668696-4c55f955-8a27-4a86-a81a-66d4b3521759.png)

        The following is a screenshot of the situation when I run the driver:
![image](https://user-images.githubusercontent.com/73341802/141668782-10d99ce1-9edb-443a-9300-e5a03e058ef3.png)
![image](https://user-images.githubusercontent.com/73341802/141668787-9ba2b750-d276-4bed-93f7-f95751ee7fcc.png)
![image](https://user-images.githubusercontent.com/73341802/141668799-937a09d2-c1a5-4e7b-8acc-cef31db929df.png)
![image](https://user-images.githubusercontent.com/73341802/141668811-080b6d08-f8e8-4f4a-bc9d-09f94f187fd0.png)
![image](https://user-images.githubusercontent.com/73341802/141668819-2ac53ada-8e96-4159-b4b9-97fc886dbd6c.png)

        I can make sure that there is no problem with my hardware (I use bynav's A3-L integrated navigation board), and other topics can output data normally (such as /gps/gps and /novatel/oem7/bestpos), I am urgent I really want to know the cause and solution of the error, I hope everyone can give me some suggestions, thank you very much!

**Comment by novatel-applications-engineering** [comment]
NovAtel ROS Driver is designed to support NovAtel product only, we don't provide support for other companies' product.
