### ISSUE TITLE
ROS2 How to build

### ISSUE THREAD

**Issue by Ahnassef** [novatel/novatel_oem7_driver#39]
**Describe the bug**
I can't build ros2 driver from source following the local environment instruction it gives the following terminal output:

![Screenshot from 2021-11-17 17-01-14](https://user-images.githubusercontent.com/4857032/142225494-c57f388c-3da3-4f32-8d50-5e59957aeae1.png)

**Steps to reproduce the behavior:**
All steps were executed smoothly except step 4 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - ROS Version: foxy

I'm aware it's still in alpha release for ros2 but I need to test the functionality. Looking forward to your feedback.

**Comment by novatel-applications-engineering** [comment]
Hi Ahnassef, thank you for contacting us.

This seems to be a dependency issue. We generally recommend using docker to build the package, ad our docker bash will setup the environment with all of the necessary dependencies.

If you would still like to install from your local environment:
From the messages shown on your terminal output, you will need to install bloom-generate and fakeroot.
