### ISSUE TITLE
hello,is this driver support oem-718d

### ISSUE THREAD

**Issue by duanqg** [novatel/novatel_oem7_driver#42]
**NOTE** 
Feature Requests are not to contain personalized information. Use these forms to submit generalized requests about the open source novatel_oem7_driver. All other inquires should be directed to private communications channels with NovAtel Customer Support.

You may reach NovAtel Customer Support by contacting support.novatel@hexagon.com. Or, you may follow the general Support process explained here: https://docs.novatel.com/OEM7/Content/Front_Matter/Customer_Support.htm

--------------

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by novatel-applications-engineering** [comment]
Yes, this driver can be used with OEM718D and any other OEM7 product. See hardware requirements here: https://wiki.ros.org/novatel_oem7_driver/hardware_setup
