### ISSUE TITLE
Build from source for ROS2 Humble on Ubuntu 22.04 (aarch64) failing

### ISSUE THREAD

**Issue by prennich** [novatel/novatel_oem7_driver#67]
**Describe the bug**
The build.sh script is failing to produce .deb files for installation.

**To Reproduce**
Here are the steps I've taken:

$ git clone https://github.com/novatel/novatel_oem7_driver.git
$ cd novatel_oem7_driver
$ git switch humble
$ rosdep install --from-paths src --ignore-src -r -y
#All required rosdeps installed successfully
$ export ROS_DISTRO=humble
$ source /opt/ros/humble/setup.bash
$ ./build.sh -f

**Expected behavior**
Was expecting .debs to be created.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 on aarch64 (RaspberryPi 4)
 - ROS Humble installed and functioning.

**Additional context**
Below is the command line output after executing ./build.sh -f:

Starting >>> novatel_oem7_msgs
[Processing: novatel_oem7_msgs]                            
[Processing: novatel_oem7_msgs]
[Processing: novatel_oem7_msgs]         
[Processing: novatel_oem7_msgs]                       
[Processing: novatel_oem7_msgs]                               
[Processing: novatel_oem7_msgs]                             
Finished <<< novatel_oem7_msgs [3min 20s]       
Starting >>> novatel_oem7_driver
[Processing: novatel_oem7_driver]           
[Processing: novatel_oem7_driver]                     
[Processing: novatel_oem7_driver]         
[Processing: novatel_oem7_driver]                 
[Processing: novatel_oem7_driver]                  
[Processing: novatel_oem7_driver]                         
[Processing: novatel_oem7_driver]                           
[Processing: novatel_oem7_driver]                      
[Processing: novatel_oem7_driver]                         
[Processing: novatel_oem7_driver]                         
[Processing: novatel_oem7_driver]                           
[Processing: novatel_oem7_driver]                  
--- stderr: novatel_oem7_driver                            
CMake Warning at /opt/ros/humble/share/gps_tools/cmake/ament_cmake_export_libraries-extras.cmake:116 (message):
  Package 'gps_tools' exports library 'gps_tools' which couldn't be found
Call Stack (most recent call first):
  /opt/ros/humble/share/gps_tools/cmake/gps_toolsConfig.cmake:41 (include)
  CMakeLists.txt:15 (find_package)

Linking to EDIE at: '/home/aloft/novatel/novatel_oem7_driver/build/novatel_oem7_driver'
Cloning into 'novatel_oem7_decoder'...
HEAD is now at ebb311d -Wno-format-security
HEAD is now at ebb311d -Wno-format-security
CMAKE Host :  Linux
CMAKE_SYSTEM_PROCESSOR:aarch64
CMAKE_LIB_SHARED:
ARCH is not Set, default to x64
ARCH is x64 & Building for 64 bit
CMAKE_C_FLAGS_DEBUG:    -g
CMAKE_CXX_FLAGS_DEBUG:  -g -std=gnu++11 -fPIC -D_LINUX_
CMAKE_C_FLAGS_RELEASE:  -s -O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:-g -Wno-write-strings -Wno-format -Wno-format-security -Wno-overflow -std=gnu++11 -fPIC -D_LINUX_ -DNDEBUG -s
CMake Deprecation Warning at lib/googletest/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at lib/googletest/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at lib/googletest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

COMPILE_DEFINITIONS = 
COMPILE_DEFINITIONS = DATADIR="/home/aloft/novatel/novatel_oem7_driver/build/novatel_oem7_driver/novatel_oem7_decoder/src/novatel_oem7_decoder/src/decoders/jsoninterface/test/resources/"
COMPILE_DEFINITIONS = DATADIR="/home/aloft/novatel/novatel_oem7_driver/build/novatel_oem7_driver/novatel_oem7_decoder/src/novatel_oem7_decoder/src/decoders/novatel/test/resources/"
COMPILE_DEFINITIONS = DATADIR="/home/aloft/novatel/novatel_oem7_driver/build/novatel_oem7_driver/novatel_oem7_decoder/src/novatel_oem7_decoder/src/hw_interface/stream_interface/test/resources/"
---
Finished <<< novatel_oem7_driver [6min 17s]

Summary: 2 packages finished [9min 37s]
  1 package had stderr output: novatel_oem7_driver
Starting >>> novatel_oem7_msgs
Finished <<< novatel_oem7_msgs [0.36s]          
Starting >>> novatel_oem7_driver
[Processing: novatel_oem7_driver]                   
[Processing: novatel_oem7_driver]                           
[Processing: novatel_oem7_driver]                             
[Processing: novatel_oem7_driver]                             
[Processing: novatel_oem7_driver]                             
[Processing: novatel_oem7_driver]                             
[Processing: novatel_oem7_driver]                             
[Processing: novatel_oem7_driver]                             
[Processing: novatel_oem7_driver]                             
Finished <<< novatel_oem7_driver [4min 48s]                   

Summary: 2 packages finished [4min 50s]
Summary: 18 tests, 0 errors, 0 failures, 0 skipped
[sudo] password for aloft: Sorry, try again.
[sudo] password for aloft: 
sudo: no password was provided
sudo: 1 incorrect password attempt
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Skip end-of-life distro "dashing"
Skip end-of-life distro "eloquent"
Add distro "foxy"
Skip end-of-life distro "galactic"
Skip end-of-life distro "groovy"
Add distro "humble"
Skip end-of-life distro "hydro"
Skip end-of-life distro "indigo"
Skip end-of-life distro "jade"
Skip end-of-life distro "kinetic"
Skip end-of-life distro "lunar"
Add distro "melodic"
Add distro "noetic"
Add distro "rolling"
updated cache in /home/aloft/.ros/rosdep/sources.cache
rm: cannot remove '*.deb': No such file or directory
rm: cannot remove 'src/*.deb': No such file or directory
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
ROS Distro index file associate with commit '91349fa4751c7a5b62b1129220148a11c693694f'
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/91349fa4751c7a5b62b1129220148a11c693694f/index-v4.yaml'
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
==> Generating debs for ubuntu:jammy for package(s) ['novatel_oem7_msgs']
No historical releaser history, using current maintainer name and email for each versioned changelog entry.
No CHANGELOG.rst found for package 'novatel_oem7_msgs'
Package 'novatel-oem7-msgs' has dependencies:
Run Dependencies:
  rosdep key           => jammy key
  rosidl_default_runtime => ['ros-humble-rosidl-default-runtime']
  std_msgs             => ['ros-humble-std-msgs']
Build and Build Tool Dependencies:
  rosdep key           => jammy key
  std_msgs             => ['ros-humble-std-msgs']
  ament_cmake          => ['ros-humble-ament-cmake']
  rosidl_default_generators => ['ros-humble-rosidl-default-generators']
==> Placing templates files in the 'debian' folder.
==> In place processing templates in 'debian' folder.
Expanding 'debian/control.em' -> 'debian/control'
Expanding 'debian/changelog.em' -> 'debian/changelog'
Expanding 'debian/copyright.em' -> 'debian/copyright'
Expanding 'debian/compat.em' -> 'debian/compat'
Expanding 'debian/source/options.em' -> 'debian/source/options'
Expanding 'debian/source/format.em' -> 'debian/source/format'
Expanding 'debian/rules.em' -> 'debian/rules'
dh binary -v --buildsystem=cmake --builddirectory=.obj-aarch64-linux-gnu
make: dh: No such file or directory
make: *** [debian/rules:27: binary] Error 127
[sudo] password for aloft: Sorry, try again.
[sudo] password for aloft: 
sudo: no password was provided
sudo: 1 incorrect password attempt
[sudo] password for aloft: Sorry, try again.
[sudo] password for aloft: 
sudo: no password was provided
sudo: 1 incorrect password attempt
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
ROS Distro index file associate with commit '91349fa4751c7a5b62b1129220148a11c693694f'
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/91349fa4751c7a5b62b1129220148a11c693694f/index-v4.yaml'
==> Generating debs for ubuntu:jammy for package(s) ['novatel_oem7_driver']
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Could not resolve rosdep key 'novatel_oem7_msgs'
Try to resolve the problem with rosdep and then continue.
Continue [Y/n]? n
GeneratorError: Error running generator: Failed to resolve rosdep key 'novatel_oem7_msgs', aborting.
/usr/bin/fakeroot: 175: debian/rules: not found
mv: cannot stat 'src/*.deb': No such file or directory

**Comment by novatel-applications-engineering** [comment]
Thank you for reaching out to us @prennich. We will work on reproducing this issue locally and provide a solution afterwards. I will update you once I learn more.

**Comment by novatel-applications-engineering** [comment]
Hi @prennich, the current solution is to change the 'rosdep.yaml' to (we will be pushing this change to humble branch, but for now you will need to do this locally):

novatel_oem7_msgs: 
    ubuntu: 
        focal:  [ros-foxy-novatel-oem7-msgs]
        jammy: [ros-humble-novatel-oem7-msgs]

Save the file, and then start the docker environment using the instruction shown in https://github.com/novatel/novatel_oem7_driver/tree/humble with command: './docker/run.sh -r amd64 humble'

Once the docker environment is built, then run: './build.sh -f'

**Comment by prennich** [comment]
Thank you. I will test this solution and report back.

**Comment by novatel-applications-engineering** [comment]
Change committed to humble branch.
