### ISSUE TITLE
Dangling '}' inside the cmakefile

### ISSUE THREAD

**Issue by VRichardJP** [novatel/novatel_oem7_driver#77]
**Describe the bug**

It does not seem to cause any harm, but there is a dangling '}' there:

https://github.com/novatel/novatel_oem7_driver/blob/99109903ae420aad96fbdf2ca93f09cbf9416a7c/src/novatel_oem7_driver/CMakeLists.txt#L185-L189

Shouldn't this be just `bin`?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by novatel-applications-engineering** [comment]
Thank you @VRichardJP for pointing this out.
This will be fixed shortly.
