### ISSUE TITLE
RAWIMU[S] Support

### ISSUE THREAD

**Issue by venabled** [novatel/novatel_oem7_driver#9]
From reading the code and the documentation, it looks like the driver does not currently support publishing of RAWIMU(S) messages from SPAN. Is this log something that could be supported in the future?

**Comment by novatel-applications-engineering** [comment]
Hi @venabled, the driver records RAWIMUSX, this is visible on Line 14 of the `oem7_msgs.yaml` file, here's a [direct link](https://github.com/novatel/novatel_oem7_driver/blob/37830e6d1d3b83e4af9107fbd3268cb15eeb525a/src/novatel_oem7_driver/config/oem7_msgs.yaml#L14).

These logs are mixed in with other log data under the `/novatel/oem7/oem7raw` ROS topic.

To extract them, you may use the method discussed on the driver's Wiki page, here:
https://wiki.ros.org/novatel_oem7_driver/runtime_operation#Recording_data_to_a_ROS_bag

If you specifically want RAWMU or RAWIMUS, you can configure the driver to additionally record that log and it too will be available in the oem7raw topic. This option is documented here:
https://wiki.ros.org/novatel_oem7_driver/configuration#Customizing_Logging_Configuration

Do you desire different functionality than this?

For reference, the RAWIMUSX log documentation is available here:
https://docs.novatel.com/OEM7/Content/SPAN_Logs/RAWIMUSX.htm
